port = 8080
db = "csv"

[csv]
	file = "data.csv"

[[language]]
	language = "en"
	headers = ["Time", "?", "something"]

[[language]]
	language = "ru"
	headers = ["Время", "Напряжение?", "Ещё что-то", "Шо это такое?", "???", "помогите"]
